export const state = () => ({
  serviceList: {
    num: ["01", "02", "03"],
    title: ["dog walking", "pet visit", "overnight care"],
    thumb: ["@/assets/imgs/service/service_01.png", "@/assets/imgs/service/service_02.png", "@/assets/imgs/service/service_03.png"],
    buttonClass: ["main__ico-walk", "main__ico-visit", "main__ico-night"],
  },

  reviewList: [
    {
      num: "01",
      name: "janedoe",
      date: "2023-11-02",
      thumb: "",
      title: `I recently used the dog care service, and I couldn't be happier! The team took excellent care of my furry friend, providing regular updates and even sending adorable photos. Highly recommended!`,
      desc: `What impressed me the most was their attention to detail. They not only followed my dog's feeding and walking schedule meticulously but also took note of his favorite toys and playtime preferences. It's these thoughtful touches that make them stand out, and I'm genuinely grateful for the personalized care they provided.`,
    },
    {
      num: "02",
      name: "happypf",
      date: "2023-12-01",
      thumb: "",
      title: `Our experience with this dog care service was fantastic. The caregivers were professional, attentive, and clearly love dogs. Our pup came back happy and healthy. A+ service!`,
      desc: `Beyond the exceptional care, what I found particularly commendable was their commitment to cleanliness. Our dog returned not only content but also freshly groomed, a surprising and delightful bonus. It's evident that they go the extra mile to ensure every aspect of our pet's well-being is considered.`,
    },
    {
      num: "03",
      name: "mike",
      date: "2023-12-01",
      thumb: "",
      title: `I'm so grateful for the peace of mind this service gave me. They not only fed and walked...`,
      desc: `One aspect that truly won me over was their communication style. I received daily updates, not just about my dog's activities but also about his mood and any noteworthy behaviors. It felt like I was kept in the loop in a way that went beyond mere logistics, reinforcing the trust I had in their care.`,
    },
    {
      num: "04",
      name: "joe",
      date: "2023-12-01",
      thumb: "",
      title: `This service is a game-changer! The convenience of having someone reliable take care of my dog while I'm away is priceless. The team is trustworthy, and my dog adores them.`,
      desc: `Adding to the convenience, what I appreciated was their adaptability. My dog has a specific diet, and they not only followed it diligently but were also accommodating when I provided some homemade treats for him. It's these small gestures that showcase their dedication to both the pet and the owner.`,
    },
    {
      num: "05",
      name: "clala",
      date: "2023-12-01",
      thumb: "",
      title: `Used this dog care service for the first time and couldn't be more pleased. The communication was excellent, and I felt reassured that my dog was in good hands. Will be a repeat customer for sure.`,
      desc: `Something that pleasantly surprised me was their commitment to environmental enrichment. They introduced new toys and games to keep my dog stimulated, and the positive impact on his mood was evident. It's clear they understand the importance of mental stimulation for a happy and healthy pet.`,
    },
    {
      num: "06",
      name: "torry",
      date: "2024-03-28",
      thumb: "",
      title: `Five stars for this dog care service! They went above and beyond, organizing fun activities for my dog. It's evident they genuinely care about the well-being and happiness of the pets they look after.`,
      desc: `Additionally, they provided a detailed activity log, outlining not just the standard care routine but also the specific adventures my dog embarked on during the day. It was like reading a personalized adventure diary for my furry friend, making their service truly unique.`,
    },
    {
      num: "07",
      name: "flo",
      date: "2024-03-28",
      thumb: "",
      title: `I travel frequently for work, and finding a reliable dog care service has been a game-changer. The team here is consistent, responsible, and treats my dog like their own. Thank you!`,
      desc: `Thank you! What stood out to me was their proactive approach to health care. They noticed a minor cut on my dog during one visit and promptly informed me, even offering to apply a pet-safe ointment. It's this level of vigilance that truly sets them apart.`,
    },
    {
      num: "08",
      name: "tom",
      date: "2023-12-01",
      thumb: "",
      title: `My dog can be a bit anxious, but the caregivers at this service were patient and understanding. They took the time to build trust, and now my dog eagerly looks forward to their visits. Great job!`,
      desc: `Furthermore, their dedication to safety was evident. They conducted a thorough pet-proofing of my home and suggested minor adjustments to ensure my dog's environment was hazard-free. It's this attention to detail that gives me confidence in their commitment to my pet's well-being.`,
    },
  ],
});
